// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/config_service.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_config_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_config_service_proto_rawDescGZIP(), []int{0}
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ServiceCode   string                 `protobuf:"bytes,3,opt,name=ServiceCode,proto3" json:"ServiceCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_config_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_config_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetServiceCode() string {
	if x != nil {
		return x.ServiceCode
	}
	return ""
}

type ServiceLists struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceLists) Reset() {
	*x = ServiceLists{}
	mi := &file_proto_config_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceLists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceLists) ProtoMessage() {}

func (x *ServiceLists) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceLists.ProtoReflect.Descriptor instead.
func (*ServiceLists) Descriptor() ([]byte, []int) {
	return file_proto_config_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceLists) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDetailRequest) Reset() {
	*x = ServiceDetailRequest{}
	mi := &file_proto_config_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDetailRequest) ProtoMessage() {}

func (x *ServiceDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDetailRequest.ProtoReflect.Descriptor instead.
func (*ServiceDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceDetailRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ServiceDetialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceInfo           `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDetialResponse) Reset() {
	*x = ServiceDetialResponse{}
	mi := &file_proto_config_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDetialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDetialResponse) ProtoMessage() {}

func (x *ServiceDetialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDetialResponse.ProtoReflect.Descriptor instead.
func (*ServiceDetialResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_service_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceDetialResponse) GetService() *ServiceInfo {
	if x != nil {
		return x.Service
	}
	return nil
}

var File_proto_config_service_proto protoreflect.FileDescriptor

const file_proto_config_service_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/config_service.proto\x12\x06config\"\a\n" +
	"\x05Empty\"S\n" +
	"\vServiceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vServiceCode\x18\x03 \x01(\tR\vServiceCode\"?\n" +
	"\fServiceLists\x12/\n" +
	"\bservices\x18\x01 \x03(\v2\x13.config.ServiceInfoR\bservices\"&\n" +
	"\x14ServiceDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x15ServiceDetialResponse\x12-\n" +
	"\aservice\x18\x01 \x01(\v2\x13.config.ServiceInfoR\aservice2\x97\x01\n" +
	"\rConfigService\x125\n" +
	"\x0eGetServiceList\x12\r.config.Empty\x1a\x14.config.ServiceLists\x12O\n" +
	"\x10GetServiceDetail\x12\x1c.config.ServiceDetailRequest\x1a\x1d.config.ServiceDetialResponseB\x0fZ\r/grpc; configb\x06proto3"

var (
	file_proto_config_service_proto_rawDescOnce sync.Once
	file_proto_config_service_proto_rawDescData []byte
)

func file_proto_config_service_proto_rawDescGZIP() []byte {
	file_proto_config_service_proto_rawDescOnce.Do(func() {
		file_proto_config_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_config_service_proto_rawDesc), len(file_proto_config_service_proto_rawDesc)))
	})
	return file_proto_config_service_proto_rawDescData
}

var file_proto_config_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_config_service_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: config.Empty
	(*ServiceInfo)(nil),           // 1: config.ServiceInfo
	(*ServiceLists)(nil),          // 2: config.ServiceLists
	(*ServiceDetailRequest)(nil),  // 3: config.ServiceDetailRequest
	(*ServiceDetialResponse)(nil), // 4: config.ServiceDetialResponse
}
var file_proto_config_service_proto_depIdxs = []int32{
	1, // 0: config.ServiceLists.services:type_name -> config.ServiceInfo
	1, // 1: config.ServiceDetialResponse.service:type_name -> config.ServiceInfo
	0, // 2: config.ConfigService.GetServiceList:input_type -> config.Empty
	3, // 3: config.ConfigService.GetServiceDetail:input_type -> config.ServiceDetailRequest
	2, // 4: config.ConfigService.GetServiceList:output_type -> config.ServiceLists
	4, // 5: config.ConfigService.GetServiceDetail:output_type -> config.ServiceDetialResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_config_service_proto_init() }
func file_proto_config_service_proto_init() {
	if File_proto_config_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_config_service_proto_rawDesc), len(file_proto_config_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_service_proto_goTypes,
		DependencyIndexes: file_proto_config_service_proto_depIdxs,
		MessageInfos:      file_proto_config_service_proto_msgTypes,
	}.Build()
	File_proto_config_service_proto = out.File
	file_proto_config_service_proto_goTypes = nil
	file_proto_config_service_proto_depIdxs = nil
}
